name: time_tracker
description: A Flutter time tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  uuid: ^4.4.0
  localstorage: ^4.0.1+4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
